version: '3'

services:
  mysql:
    image: mysql
    ports:
      - "9000:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: FALSE
      MYSQL_RANDOM_ROOT_PASSWORD: TRUE
    networks:
      - backend

  payment:
    build:
      context: payment-service/
      dockerfile: Dockerfile
    volumes:
      - ./payment-service:/app
    depends_on:
      - rabbitmq
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

networks:
  backend:
    driver: bridge
    name: backend
