version: '3'

services:
  mysql:
    image: mysql
    ports:
      - "9000:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: FALSE
      MYSQL_RANDOM_ROOT_PASSWORD: TRUE
    networks:
      - backend

  front:
    build: ./frontend
    container_name: react-front
    volumes:
      - ./frontend/cypress/videos:/usr/src/app/cypress/videos
    ports:
      - "8000:8000"
    command: npm start
    networks:
      - backend

networks:
  backend:
    driver: bridge
    name: backend
