version: '3'

services:
  mysql:
    image: mysql
    ports:
      - "9000:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: FALSE
      MYSQL_RANDOM_ROOT_PASSWORD: TRUE
    networks:
      - backend

networks:
  backend:
